# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Evaluate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from contextlib import redirect_stderr
from msilib.schema import Error
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 450)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb1 = QtWidgets.QComboBox(Dialog)
        self.cb1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb1.sizePolicy().hasHeightForWidth())
        self.cb1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.cb1.setFont(font)
        self.cb1.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.cb1.setEditable(True)
        import sqlite3
        conn = sqlite3.connect('Fantacy_Cricket.db')
        sql = "select name from team"
        cur = conn.execute(sql)
        for row in cur:
            self.cb1.addItem(row[0])
        self.cb1.setObjectName("cb1")
        self.horizontalLayout.addWidget(self.cb1)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cb2 = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb2.sizePolicy().hasHeightForWidth())
        self.cb2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.cb2.setFont(font)
        self.cb2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.cb2.setEditable(True)
        self.cb2.setObjectName("cb2")
        self.cb2.addItem("1st_t20_match")
        self.cb2.addItem("2nd_t20_match")
        self.cb2.addItem("3rd_t20_match")
        self.horizontalLayout.addWidget(self.cb2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.list1 = QtWidgets.QListWidget(Dialog)
        self.list1.setObjectName("list1")
        self.verticalLayout.addWidget(self.list1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.l1 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:None;")
        self.l1.setObjectName("l1")
        self.horizontalLayout_2.addWidget(self.l1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.list2 = QtWidgets.QListWidget(Dialog)
        self.list2.setObjectName("list2")
        self.verticalLayout_2.addWidget(self.list2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.clicked.connect(self.calculateScore)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Evaluate"))
        self.label.setText(_translate("Dialog", "Evaluate the performance of fantacy team"))
        self.cb1.setCurrentText(_translate("Dialog", "Select Team"))
        self.cb2.setCurrentText(_translate("Dialog", "Select Match"))
        #self.cb2.setItemText(0, _translate("Form", "match"))
        self.label_4.setText(_translate("Dialog", "Players"))
        self.label_5.setText(_translate("Dialog", "Points"))
        self.pushButton.setText(_translate("Dialog", "Calculate Score"))


    def calculateScore(self):
        import sqlite3
        conn = sqlite3.connect('Fantacy_Cricket.db')
        try:
            team=self.cb1.currentText()
            self.list1.clear()
            sql1 = "select player,value from team where name='"+team+"'"
            cur=conn.execute(sql1)
            row = cur.fetchone()
            selected = row[0].split(',')
            self.list1.addItems(selected)
            self.list2.clear()
            totalScore = 0
            match = self.cb2.currentText()
            for i in range(self.list1.count()):
                playerTotal, batScore, bowlScore, fieldScore=0,0,0,0
                nm = self.list1.item(i).text()
                sql2 = "select * from '"+match+"' where player = '"+nm+"'"
                curs =conn.execute(sql2)
                result = curs.fetchone()
                if result[1]>0:
                    strikRate = result[1]/result[2]
                else:
                    strikRate = 0
                if result[7]>0:
                    ecoRate = result[7]/result[5]
                else:
                    ecoRate = 0
                batScore = result[1]//2 + (5 if result[1] >= 50 else 0) + ( 10 if result[1] >= 100 else 0) + (2 if strikRate >=80 and strikRate <= 100 else 0) + ( 4 if strikRate > 100 else 0) + result[3] + (result[4]*2)
                bowlScore = (10 * result[8]) + (5 if result[1] >= 3 else 0) + (10 if result[8] >= 5 else 0) + (4 if ecoRate >= 3.5 and ecoRate <= 4.5 else 0) + (7 if ecoRate >= 2 and ecoRate < 3.5 else 0) + (10 if ecoRate < 2 and ecoRate > 0 else 0)
                fieldScore = (result[9] + result[10] + result[11]) * 10
                playerTotal = batScore + bowlScore + fieldScore
                totalScore = totalScore + playerTotal
                self.list2.addItem(str(playerTotal))
            self.l1.setText(str(totalScore))

        except:
            msg = "please check select team and match."
            self.shwdlg(msg)

    def shwdlg(self,msg):
        Dlg=QtWidgets.QMessageBox()
        Dlg.setText(msg)
        Dlg.setWindowTitle("Fantacy Cricket Game")
        ret=Dlg.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
