# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fantacy_Cricket.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 120, 215);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1.sizePolicy().hasHeightForWidth())
        self.t1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.t1.setFont(font)
        self.t1.setStyleSheet("border:none;")
        self.t1.setText("")
        self.t1.setObjectName("t1")
        self.horizontalLayout_2.addWidget(self.t1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2.sizePolicy().hasHeightForWidth())
        self.t2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.t2.setFont(font)
        self.t2.setStyleSheet("border:none;")
        self.t2.setObjectName("t2")
        self.horizontalLayout_2.addWidget(self.t2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.t3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3.sizePolicy().hasHeightForWidth())
        self.t3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.t3.setFont(font)
        self.t3.setStyleSheet("border:none;")
        self.t3.setObjectName("t3")
        self.horizontalLayout_2.addWidget(self.t3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.t4 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t4.sizePolicy().hasHeightForWidth())
        self.t4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.t4.setFont(font)
        self.t4.setStyleSheet("border:none;")
        self.t4.setObjectName("t4")
        self.horizontalLayout_2.addWidget(self.t4)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.t5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.t5.setFont(font)
        self.t5.setStyleSheet("border:none;")
        self.t5.setText("")
        self.t5.setObjectName("t5")
        self.horizontalLayout_3.addWidget(self.t5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb1 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rb1.setFont(font)
        self.rb1.setObjectName("rb1")
        self.horizontalLayout.addWidget(self.rb1)
        self.rb2 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rb2.setFont(font)
        self.rb2.setObjectName("rb2")
        self.horizontalLayout.addWidget(self.rb2)
        self.rb3 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rb3.setFont(font)
        self.rb3.setObjectName("rb3")
        self.horizontalLayout.addWidget(self.rb3)
        self.rb4 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rb4.setFont(font)
        self.rb4.setObjectName("rb4")
        self.rb1.toggled.connect(self.ctg)
        self.rb2.toggled.connect(self.ctg)
        self.rb3.toggled.connect(self.ctg)
        self.rb4.toggled.connect(self.ctg)
        self.horizontalLayout.addWidget(self.rb4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.l1 = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.l1.itemDoubleClicked.connect(self.removelist1)
        self.verticalLayout.addWidget(self.l1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.t6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.t6.setFont(font)
        self.t6.setStyleSheet("border:none;")
        self.t6.setObjectName("t6")
        self.horizontalLayout_4.addWidget(self.t6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem11 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.t7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.t7.setFont(font)
        self.t7.setStyleSheet("border:none;")
        self.t7.setObjectName("t7")
        self.horizontalLayout_5.addWidget(self.t7)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.l2 = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.l2.itemDoubleClicked.connect(self.removelist2)
        self.verticalLayout_3.addWidget(self.l2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 634, 26))
        self.menubar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(240, 240, 240);")
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.menumenu.setObjectName("menumenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_team = QtWidgets.QAction(MainWindow)
        self.actionNew_team.setShortcut("Ctrl+N")
        self.actionNew_team.setObjectName("actionNew_team")
        self.actionOpen_team = QtWidgets.QAction(MainWindow)
        self.actionOpen_team.setShortcut("Ctrl+O")
        self.actionOpen_team.setObjectName("actionOpen_team")
        self.actionSave_team = QtWidgets.QAction(MainWindow)
        self.actionSave_team.setShortcut("Ctrl+S")
        self.actionSave_team.setObjectName("actionSave_team")
        self.actionEvaluate = QtWidgets.QAction(MainWindow)
        self.actionEvaluate.setShortcut("Ctrl+E")
        self.actionEvaluate.setObjectName("actionEvaluate")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setShortcut("Ctrl+Q")
        self.actionQuit.setObjectName("actionQuit")
        self.menumenu.addAction(self.actionNew_team)
        self.menumenu.addAction(self.actionOpen_team)
        self.menumenu.addAction(self.actionSave_team)
        self.menumenu.addAction(self.actionEvaluate)
        self.menumenu.addAction(self.actionQuit)
        self.menumenu.triggered[QtWidgets.QAction].connect(self.menuFunction)
        self.menubar.addAction(self.menumenu.menuAction())
        self.bat=0
        self.bowl=0
        self.AR=0
        self.WK=0
        self.avl=1000
        self.used=0
        self.status()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.customContextMenuRequested.connect(self.context_menu)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fantacy Cricket"))
        self.label.setText(_translate("MainWindow", "Your Selections:"))
        self.label_2.setText(_translate("MainWindow", "Batsman:"))
        self.label_3.setText(_translate("MainWindow", "Bowlers:"))
        self.label_4.setText(_translate("MainWindow", "Allrounder:"))
        self.label_5.setText(_translate("MainWindow", "Wicketkipper:"))
        self.label_6.setText(_translate("MainWindow", "Point Available:"))
        self.rb1.setText(_translate("MainWindow", "BAT"))
        self.rb2.setText(_translate("MainWindow", "BOW"))
        self.rb3.setText(_translate("MainWindow", "AR"))
        self.rb4.setText(_translate("MainWindow", "WK"))
        self.label_7.setText(_translate("MainWindow", "Used Point:"))
        self.label_8.setText(_translate("MainWindow", "Team Name:"))
        self.menumenu.setTitle(_translate("MainWindow", "menu"))
        self.actionNew_team.setText(_translate("MainWindow", "New team"))
        self.actionOpen_team.setText(_translate("MainWindow", "Open team"))
        self.actionSave_team.setText(_translate("MainWindow", "Save team"))
        self.actionEvaluate.setText(_translate("MainWindow", "Evaluate"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


    def menuFunction(self,action):
        txt=action.text()
        if txt=="New team":
            self.bat=0
            self.bowl=0
            self.AR=0
            self.WK=0
            self.avl=1000
            self.used=0
            self.l1.clear()
            self.l2.clear()
            self.t7.setText('')
            self.status()
            text, ok = QtWidgets.QInputDialog.getText(MainWindow ,'Fantacy Cricket Game', '''Create New Team.\n\nEnter team name:''')
            if ok:
                self.t7.setText(str(text))

        if txt == "Save team":
            count = self.l2.count()
            select=""
            for i in range(count):
                select = select+self.l2.item(i).text()
                if i < count-1:
                    select =select+","
            self.save_team(self.t7.text(),select,str(self.used))

        if txt == "Open team":
            self.bat=0
            self.bowl=0
            self.AR=0
            self.WK=0
            self.avl=1000
            self.used=0
            self.l1.clear()
            self.l2.clear()
            self.t7.setText('')
            self.status()
            self.open_team()

        if txt == "Evaluate":
            from Evaluate import Ui_Dialog
            Dialog = QtWidgets.QDialog()
            ui = Ui_Dialog()
            ui.setupUi(Dialog)
            ret=Dialog.exec()

        if txt == "Quit":
            sys.exit()

    
    def save_team(self,nm,string,val):
        if self.bat + self.bowl + self.AR + self.WK != 11:
            msg ="Insufficient Players."
            self.shwdlg(msg)
            return
        try:
            sql = "insert into team (name, player, value) values('"+nm+"', '"+string+"','"+val+"');"
            curs = con.execute(sql)
            con.commit()
            self.shwdlg("Team saved succesfully")
        except:
            self.shwdlg('''Something is wrong, Team not saved.
            Please check''')
            con.rollback()
          

    def open_team(self):
        sql = "select name from team"
        curs = con.execute(sql)
        teams=[]
        for row in curs:
            teams.append(row[0])
        team, ok = QtWidgets.QInputDialog.getItem(MainWindow ,'Fantacy Cricket Game', 'Select team name:', teams, 0, False)
        if ok and team:
            self.t7.setText(team)
        sql1 = "select player,value from team where name='"+team+"'"
        cur = con.execute(sql1)
        row = cur.fetchone()
        select = row[0].split(',')
        self.l2.addItems(select)
        self.used = row[1]
        self.avl = 1000-self.used
        count = self.l2.count()
        for i in range(count):
            player = self.l2.item(i).text()
            sql2 = "select ctg from stats where Player='"+player+"'"
            curs = con.execute(sql2)
            result = curs.fetchone()
            ctgr = result[0]
            if ctgr == 'bat':self.bat += 1
            if ctgr == 'bowl':self.bowl += 1
            if ctgr == 'AR':self.WK += 1
            if ctgr == 'WK':self.WK += 1
        self.status()


    def context_menu(MainWindow):
        MainWindow.menu=QtWidgets.QMenu()


    
    def ctg(self):
        ctgr = ''
        if self.rb1.isChecked()==True:ctgr='bat'
        if self.rb2.isChecked()==True:ctgr='bowl'
        if self.rb3.isChecked()==True:ctgr='AR'
        if self.rb4.isChecked()==True:ctgr='WK'
        self.listFill(ctgr)

    
    def listFill(self,ctgr):
        if self.t7.text()=='':
            self.shwdlg("Enter team name.")
            return
        self.l1.clear()
        cursor = con.execute("select Player from stats where ctg='"+ctgr+"'")
        for row in cursor:
            select=[]
            for i in range(self.l2.count()):
                select.append(self.l2.item(i).text())
            if row[0] not in select:self.l1.addItem(row[0])

    
    def removelist1(self, item):
        ctgr=''
        if self.rb1.isChecked()==True:ctgr='bat'
        if self.rb2.isChecked()==True:ctgr='bowl'
        if self.rb3.isChecked()==True:ctgr='AR'
        if self.rb4.isChecked()==True:ctgr='WK'
        rete=self.criteria(ctgr,item)
        if rete==True:
            self.l1.takeItem(self.l1.row(item))
            self.l2.addItem(item.text())
            self.status()


    def criteria(self, ctgr, item):
        msg=''
        if ctgr=='bat' and self.bat >= 5:msg = "Batsman not more than 5"
        if ctgr=='bowl' and self.bowl >= 5:msg = "Bowler not more than 5"
        if ctgr=='AR' and self.AR >= 3:msg = "Allrounder not more than 3"
        if ctgr=='WK' and self.WK >= 1:msg = "Wicketkipper not more than 1"
        if msg != '':
            self.shwdlg(msg)
            return False
        if self.l2.count() >= 11:
            msg='''Sorry, you have selected 11 players.
             Please check.'''
            self.shwdlg(msg)
            return False
        
        cursor = con.execute("select Player,value from stats where Player = '"+item.text()+"'")
        result = cursor.fetchone()
        self.avl = self.avl - int(result[1])
        if self.avl <= 0:
            self.avl = self.avl + int(result[1])
            msg = "You have exhausted your point."
            self.shwdlg(msg)
            return False
        self.used = self.used + int(result[1])
        if ctgr == 'bat':self.bat += 1
        if ctgr == 'bowl':self.bowl += 1
        if ctgr == 'AR':self.AR += 1
        if ctgr == 'WK':self.WK += 1
        return True
 
    def status(self):
        self.t1.setText(str(self.bat))
        self.t2.setText(str(self.bowl))
        self.t3.setText(str(self.AR))
        self.t4.setText(str(self.WK))
        self.t5.setText(str(self.avl))
        self.t6.setText(str(self.used))

    def removelist2(self, item):
        self.l2.takeItem(self.l2.row(item))
        cursor = con.execute("select Player,value,ctg from stats where Player = '"+item.text()+"'")
        result = cursor.fetchone()
        self.avl = self.avl + int(result[1])
        self.used = self.used - int(result[1])
        ctgr = result[2]
        if ctgr == 'bat':
            self.bat -= 1
            if self.rb1.isChecked() == True:self.l1.addItem(item.text())
        if ctgr == 'bowl':
            self.bowl -= 1
            if self.rb2.isChecked() == True:self.l1.addItem(item.text())
        if ctgr == 'AR':
            self.AR -= 1
            if self.rb3.isChecked() == True:self.l1.addItem(item.text())
        if ctgr == 'WK':
            self.WK -= 1
            if self.rb4.isChecked() == True:self.l1.addItem(item.text())
        self.status()

        

    def shwdlg(self,msg):
        Dlg=QtWidgets.QMessageBox()
        Dlg.setText(msg)
        Dlg.setWindowTitle("Fantacy Cricket Game")
        ret=Dlg.exec()


if __name__ == "__main__":
    import sqlite3
    con = sqlite3.connect('Fantacy_Cricket.db')
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
